# Generated by Django 2.2 on 2019-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxbinaryapi', '0002_auto_20190408_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickhistory',
            name='time',
            field=models.DateTimeField(unique=True),
        ),
    ]
